################################# Default configuration ###################
baseURL = "https://jingyunkeji.com/"
title = "精云科技"
theme = "meghna-hugo"
themesDir = "./themes"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
defaultContentLanguage = "zh-cn"
publishdir = "docs"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### Chinese Navigation ########################
[[Languages.zh-cn.menu.main]]
name = "关于"
url = "#about"
weight = 1

[[Languages.zh-cn.menu.main]]
name = "服务"
url = "#services"
weight = 2

# [[Languages.zh-cn.menu.main]]
# name = "解决方案"
# url = "#portfolio"
# weight = 3
#
# [[Languages.zh-cn.menu.main]]
# name = "团队"
# url = "#team"
# weight = 4
#
# [[Languages.zh-cn.menu.main]]
# name = "定价"
# url = "#pricing"
# weight = 5

[[Languages.zh-cn.menu.main]]
name = "博客"
url = "#blog"
weight = 6

[[Languages.zh-cn.menu.main]]
name = "联系"
url = "#contact"
weight = 7


################### English Navigation ########################
[[Languages.en.menu.main]]
name = "about"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "portfolio"
url = "#portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "team"
url = "#team"
weight = 4

[[Languages.en.menu.main]]
name = "pricing"
url = "#pricing"
weight = 5

[[Languages.en.menu.main]]
name = "blog"
url = "#blog"
weight = 6

[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 7

[[Languages.en.menu.main]]
name = "themefisher"
url = "https://themefisher.com/"
weight = 8


################### French Navigation ########################
[[Languages.fr.menu.main]]
name = "sur"
url = "#about"
weight = 1

[[Languages.fr.menu.main]]
name = "un service"
url = "#services"
weight = 2

[[Languages.fr.menu.main]]
name = "portefeuille"
url = "#portfolio"
weight = 3

[[Languages.fr.menu.main]]
name = "équipe"
url = "#team"
weight = 4

[[Languages.fr.menu.main]]
name = "tarification"
url = "#pricing"
weight = 5

[[Languages.fr.menu.main]]
name = "blog"
url = "#blog"
weight = 6

[[Languages.fr.menu.main]]
name = "contact"
url = "#contact"
weight = 7

############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "南京精云科技有限公司 （jingyun tech）"
author = "LeoWang"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

# [[params.social]]
# icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
# link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

# [[params.social]]
# icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
# link = "#"


################################ Chinese Language ########################
[Languages.zh-cn]
languageName = "简体中文"
languageCode = "zh-cn"
contentDir = "content/chinese"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2021 南京精云科技有限公司"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; 2021 jingyun tech"

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3
home = "Accueil"
copyright = "Copyright &copy; 2021 jingyun tech"

